### ISSUE TITLE
Migrate to pact-foundation and update to use pact-net v4 latest

### ISSUE THREAD

**Issue by YOU54F** [DiUS/pact-workshop-dotnet-core-v3#6]
- Migrate to pact-foundation
- Update to use pact-net v4 now that is in GA
  - [Upgrade guide](https://github.com/pact-foundation/pact-net/blob/master/docs/upgrading-to-4.md)

**Comment by YOU54F** [comment]
Created a new repo under the pact-foundation org with changes in #8 applied.

It may be worth updating readme to point at the new readme, and archiving this to avoid confusion

**Comment by mefellows** [comment]
Thanks Yousaf!

**Comment by YOU54F** [comment]
Migrated to https://github.com/pact-foundation/pact-workshop-dotnet

Closing down this PR 👍🏾
